### ISSUE TITLE
INI parser failed for alphanumeric string

### ISSUE THREAD

**Issue by yentsun** [yentsun/config#6]
Failing string:
```ini
token = 6606cec44b18aaca3ad82d7f16194dd4
```

```
INI parser failed 'Expected ".", "\n", "\r", "\r\n", or [0-9] but "c" found.'
    at config.ini:24:13
    at peg$buildStructuredError (node_modules/yt-config/parser.js:346:12)
    at peg$parse (node_modules/yt-config/parser.js:1323:11)
    at Promise (node_modules/yt-config/index.js:15:28)
    at <anonymous>
```

**Comment by yentsun** [comment]
fixed in v4.0.1
