### ISSUE TITLE
INI parser failed for inline comment

### ISSUE THREAD

**Issue by yentsun** [yentsun/config#7]
Failing comment line
```ini
[default.service]
# test credentials:
sid = AZ70da40046b1e2207ffdb7d4e7635c40z
```
Error message 
```
INI parser failed 'Expected [a-zA-Z0-9_[\] ] but "#" found.'
    at config.ini:23:1
    at peg$buildStructuredError (node_modules/yt-config/parser.js:346:12)
    at peg$parse (node_modules/yt-config/parser.js:1323:11)
    at Promise (node_modules/yt-config/index.js:15:28)
    at <anonymous>

```

**Comment by yentsun** [comment]
Fixed in v4.0.1
